version: '3.8'

services:
  node1:
    image: parity/substrate:latest
    container_name: node1
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    volumes:
      - ./data/node1:/chain-data
    environment:
      - NETWORK=local
      - CHAINSPEC=dev
    command: --chain dev
  node2:
    image: parity/substrate:latest
    container_name: node2
    ports:
      - "30334:30333"
      - "9934:9933"
      - "9945:9944"
    volumes:
      - ./data/node2:/chain-data
    environment:
      - NETWORK=local
      - CHAINSPEC=dev
    command: --chain dev
  node3:
    image: parity/substrate:latest
    container_name: node3
    ports:
      - "30335:30333"
      - "9935:9933"
      - "9946:9944"
    volumes:
      - ./data/node3:/chain-data
    environment:
      - NETWORK=local
      - CHAINSPEC=dev
    command: --chain dev