version: '3.8'

services:
  node1:
    image: parity/substrate:latest
    container_name: node1
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
      - "8080:8080"
      - "9947:9947"
    volumes:
      - ./data/node1:/chain-data
    environment:
      - NETWORK=local
      - CHAINSPEC=dev
    command: --validator --chain dev --name node1 --alice --unsafe-rpc-external --rpc-methods unsafe --rpc-cors all

  node2:
    image: parity/substrate:latest
    container_name: node2
    ports:
      - "30334:30333"
      - "9934:9933"
      - "9945:9944"
      - "8081:8080"
      - "9948:9947"
    volumes:
      - ./data/node2:/chain-data
    environment:
      - NETWORK=local
      - CHAINSPEC=dev
    command: --validator --chain dev --name node2 --bob

  node3:
    image: parity/substrate:latest
    container_name: node3
    ports:
      - "30335:30333"
      - "9935:9933"
      - "9946:9944"
      - "8082:8080"
      - "9949:9947"
    volumes:
      - ./data/node3:/chain-data
    environment:
      - NETWORK=local
      - CHAINSPEC=dev
    command: --validator --chain dev --name node3 --charlie

  explorer:
    image: jacogr/polkadot-js-apps:latest
    container_name: polkadot-explorer
    ports:
      - "3000:80"
    environment:
      - WS_URL=ws://localhost:9944
      - WS_PORT=9944
    extra_hosts:
      - "host.docker.internal:host-gateway"